package com.localphotoai.photomanager.data.database.entity

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Locally persisted metadata for one photo discovered via MediaStore. [mediaStoreId] — the row
 * id from `MediaStore.Images.Media._ID` — is used directly as the primary key (rather than a
 * separate autogenerated id) so `@Upsert` correctly matches and updates existing rows by
 * MediaStore identity instead of always inserting new ones. Only metadata is stored here; [uri]
 * is a reference, the image bytes are never copied into app storage.
 */
@Entity(
    tableName = "photos",
    indices = [
        Index("dateTakenMs"),
        Index(value = ["latitude", "longitude"]),
        Index("contentHash"),
    ],
)
data class PhotoEntity(
    @PrimaryKey val mediaStoreId: Long,
    val uri: String,
    val filename: String,
    val mimeType: String,
    val sizeBytes: Long,
    val width: Int,
    val height: Int,
    val dateAddedMs: Long,
    val dateModifiedMs: Long,
    val dateTakenMs: Long?,
    val orientationDegrees: Int,
    val latitude: Double?,
    val longitude: Double?,
    val lastIndexedAtMs: Long,
    val indexError: String?,
    /** Null until face detection has run for this row; reset to null whenever the row is re-upserted. */
    val facesDetectedAt: Long? = null,
    val faceDetectionError: String? = null,
    /** Null until hashing has run for this row; reset to null whenever the row is re-upserted. */
    val contentHash: String? = null,
    val perceptualHash: Long? = null,
    val hashError: String? = null,
    val similarityEmbeddingVersion: Int? = null,
    val similarityEmbeddingError: String? = null,
    val relativePath: String? = null,
)
