package com.localphotoai.photomanager.domain.face

import com.localphotoai.photomanager.domain.photo.IndexingProgress
import kotlinx.coroutines.flow.Flow

/**
 * Access to face-embedding results and pipeline state. Implemented in `:data:database` (Room
 * only). A face needs (re-)embedding whenever its stored `embeddingVersion` differs from the
 * current model version — including faces that have never been embedded (`null`) and faces
 * whose embedding was generated by a now-superseded model.
 */
interface FaceEmbeddingRepository {

    suspend fun fetchFacesNeedingEmbedding(currentModelVersion: Int): List<FaceForEmbedding>

    suspend fun saveEmbedding(embedding: FaceEmbedding)

    /** Marks [faceId] as attempted at [modelVersion] with [error] set — no retry until the model version changes. */
    suspend fun markEmbeddingFailed(faceId: Long, modelVersion: Int, error: String)

    fun observeEmbeddingProgress(): Flow<IndexingProgress>

    suspend fun updateEmbeddingProgress(progress: IndexingProgress)
}
